### ISSUE TITLE
[FEATURE] - v1.0.0 Settings Page + Refactor + GA4

### ISSUE THREAD

**Issue by 444B** [444B/streamlit-analytics2#53]
# Issue description
Currently, there is a growing need to allow developers to customize streamlit. Some existing features are:
- password protection
- firestore as storage for logs
- save location of local json for logs

However, there are a few requests for new features, outlined below.

# Suggested fix
### Primary
- [ ] #57
- [x] #54
- [x] Separate between application and tracking logic
- [x] settings page for configuration

### Added features: - (dependent on Primary)
- [ ] More granular timestamps - #31 
- [x] GA4 support - #16 
- [ ] track all new widgets - #46

### Refactor - (dependent on Primary)
- [ ] multi-page tracking - #47
- [ ] track inputs with same name - #26 
- [ ] traffic plot improvement  (originally # 18)
- [ ] efficient tracking of multiselect (originally # 17)
- [ ] Add streamlits AppTest framework for pytest coverage
